# coding: utf-8

"""
    MINT Data Catalog

    API Documentation for MINT Data Catalog  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: danf@usc.edu
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import datacatalog
from datacatalog.models.inline_object1 import InlineObject1  # noqa: E501
from datacatalog.rest import ApiException


class TestInlineObject1(unittest.TestCase):
    """InlineObject1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineObject1(self):
        """Test InlineObject1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = datacatalog.models.inline_object1.InlineObject1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
