# coding: utf-8

"""
    MINT Data Catalog

    API Documentation for MINT Data Catalog  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: danf@usc.edu
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import datacatalog
from datacatalog.models.variable import Variable  # noqa: E501
from datacatalog.rest import ApiException


class TestVariable(unittest.TestCase):
    """Variable unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVariable(self):
        """Test Variable"""
        # FIXME: construct object with mandatory attributes with example values
        # model = datacatalog.models.variable.Variable()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
