# coding: utf-8

"""
    MINT Data Catalog

    API Documentation for MINT Data Catalog  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: danf@usc.edu
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import datacatalog
from datacatalog.models.inline_object4 import InlineObject4  # noqa: E501
from datacatalog.rest import ApiException


class TestInlineObject4(unittest.TestCase):
    """InlineObject4 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineObject4(self):
        """Test InlineObject4"""
        # FIXME: construct object with mandatory attributes with example values
        # model = datacatalog.models.inline_object4.InlineObject4()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
