# coding: utf-8

"""
    MINT Data Catalog

    API Documentation for MINT Data Catalog  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: danf@usc.edu
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import datacatalog
from datacatalog.api.resources_api import ResourcesApi  # noqa: E501
from datacatalog.rest import ApiException


class TestResourcesApi(unittest.TestCase):
    """ResourcesApi unit test stubs"""

    def setUp(self):
        self.api = datacatalog.api.resources_api.ResourcesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_resource_info(self):
        """Test case for get_resource_info

        Detailed information about the resource  # noqa: E501
        """
        pass

    def test_register_resources(self):
        """Test case for register_resources

        Create resource record(s)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
