# coding: utf-8

"""
    MINT Data Catalog

    API Documentation for MINT Data Catalog  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: danf@usc.edu
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import datacatalog
from datacatalog.api.variables_api import VariablesApi  # noqa: E501
from datacatalog.rest import ApiException


class TestVariablesApi(unittest.TestCase):
    """VariablesApi unit test stubs"""

    def setUp(self):
        self.api = datacatalog.api.variables_api.VariablesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_variable_info(self):
        """Test case for get_variable_info

        Detailed information about the variable  # noqa: E501
        """
        pass

    def test_register_variables(self):
        """Test case for register_variables

        Create variable record(s)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
