# coding: utf-8

"""
    MINT Data Catalog

    API Documentation for MINT Data Catalog  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: danf@usc.edu
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import datacatalog
from datacatalog.models.provenance import Provenance  # noqa: E501
from datacatalog.rest import ApiException


class TestProvenance(unittest.TestCase):
    """Provenance unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProvenance(self):
        """Test Provenance"""
        # FIXME: construct object with mandatory attributes with example values
        # model = datacatalog.models.provenance.Provenance()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
