# coding: utf-8

"""
    MINT Data Catalog

    API Documentation for MINT Data Catalog  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: danf@usc.edu
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class StandardVariable(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'record_id': 'str',
        'name': 'str',
        'ontology': 'str',
        'uri': 'str'
    }

    attribute_map = {
        'record_id': 'record_id',
        'name': 'name',
        'ontology': 'ontology',
        'uri': 'uri'
    }

    def __init__(self, record_id=None, name=None, ontology=None, uri=None):  # noqa: E501
        """StandardVariable - a model defined in OpenAPI"""  # noqa: E501

        self._record_id = None
        self._name = None
        self._ontology = None
        self._uri = None
        self.discriminator = None

        self.record_id = record_id
        self.name = name
        self.ontology = ontology
        self.uri = uri

    @property
    def record_id(self):
        """Gets the record_id of this StandardVariable.  # noqa: E501

        Unique identifier  # noqa: E501

        :return: The record_id of this StandardVariable.  # noqa: E501
        :rtype: str
        """
        return self._record_id

    @record_id.setter
    def record_id(self, record_id):
        """Sets the record_id of this StandardVariable.

        Unique identifier  # noqa: E501

        :param record_id: The record_id of this StandardVariable.  # noqa: E501
        :type: str
        """
        if record_id is None:
            raise ValueError("Invalid value for `record_id`, must not be `None`")  # noqa: E501

        self._record_id = record_id

    @property
    def name(self):
        """Gets the name of this StandardVariable.  # noqa: E501

        Display name/title/label of the standard variable  # noqa: E501

        :return: The name of this StandardVariable.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this StandardVariable.

        Display name/title/label of the standard variable  # noqa: E501

        :param name: The name of this StandardVariable.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def ontology(self):
        """Gets the ontology of this StandardVariable.  # noqa: E501

        Name of the ontology under which this standard variable is defined  # noqa: E501

        :return: The ontology of this StandardVariable.  # noqa: E501
        :rtype: str
        """
        return self._ontology

    @ontology.setter
    def ontology(self, ontology):
        """Sets the ontology of this StandardVariable.

        Name of the ontology under which this standard variable is defined  # noqa: E501

        :param ontology: The ontology of this StandardVariable.  # noqa: E501
        :type: str
        """
        if ontology is None:
            raise ValueError("Invalid value for `ontology`, must not be `None`")  # noqa: E501

        self._ontology = ontology

    @property
    def uri(self):
        """Gets the uri of this StandardVariable.  # noqa: E501

        public URI that defines this standard variable  # noqa: E501

        :return: The uri of this StandardVariable.  # noqa: E501
        :rtype: str
        """
        return self._uri

    @uri.setter
    def uri(self, uri):
        """Sets the uri of this StandardVariable.

        public URI that defines this standard variable  # noqa: E501

        :param uri: The uri of this StandardVariable.  # noqa: E501
        :type: str
        """
        if uri is None:
            raise ValueError("Invalid value for `uri`, must not be `None`")  # noqa: E501

        self._uri = uri

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, StandardVariable):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
